#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    autocomplete_method = "coc"
    snippet_engine = "ultisnips"

    enable_neomake = false
    enable_ale     = true

    colorscheme = "oceanic_material"
    # colorscheme = "gruvbox"
    # colorscheme = "one"
    # colorscheme = "kolor"
    # colorscheme = "darcula"
    # colorscheme = "srcery"
    # colorscheme = "space-vim-dark"
    # colorscheme = "space_vim_theme"



    colorscheme_bg = "white"
    # enable_cursorcolumn = true
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # sidebar_width = 33
    # relativenumber=false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    # options for statusline
    # Set the statusline separators of statusline, default is "arrow"
    statusline_separator = "arrow"
    # Set the statusline separators of inactive statusline
    statusline_inactive_separator = "bar"

    # Set SpaceVim buffer index type
    buffer_index_type = 1
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1

    #left sections of statusline
    # statusline_left_sections = [
       # gruvbox-material'
    colorscheme_bg = "dark"
    # enable_cursorcolumn = true
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # sidebar_width = 33
    # relativenumber=false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    # options for statusline
    # Set the statusline separators of statusline, default is "arrow"
    statusline_separator = "arrow"
    # Set the statusline separators of inactive statusline
    statusline_inactive_separator = "bar"

    # Set SpaceVim buffer index type
    buffer_index_type = 1
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1

    #left sections of statusline
    # statusline_left_sections = [
       # 'winnr',
       # 'major mode',
       # 'filename',
       # 'fileformat',
       # 'minor mode lighters',
       # 'version control info',
       # 'search status'
    # ]

    # right sections of statusline
    statusline_right_sections = [
       'version control info',
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]

    enable_tabline_filetype_icon = true
    enable_vimfiler_filetypeicon = true
    enable_statusline_mode = false

    # filetree_direction = "left"
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
# [[layers]]
  # name = 'coc'
  # auto-completion-return-key-behavior = "complete"
  # auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = "lsp"
  # filetypes = [
    # "ruby",
    # "javascript"
  # ]


[[layers]]
  name = "test"

# [[layers]]
  # name = "lang#html"
[[layers]]
  name = "core#statusline"

[[layers]]
  name = "autocomplete"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 50

[[layers]]
  name = "lang#ruby"

# [[layers]]
  # name = "lang#javascript"
  # enable_flow_syntax = true

[[custom_plugins]]
  name= "ryanoasis/vim-devicons"
  merged = 0
[[custom_plugins]]
  name= "tpope/vim-fugitive"
  merged = 0
[[custom_plugins]]
  name= "lambdalisue/glyph-palette.vim"
  merged = 0
[[custom_plugins]]
  name = "ctrlpvim/ctrlp.vim"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-rails"
  merged = 0
[[custom_plugins]]
  name = "slim-template/vim-slim"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-haml"
  merged = 0
[[custom_plugins]]
  name = "sunaku/vim-ruby-minitest"
  merged = 0
[[custom_plugins]]
  name = "lilydjwg/colorizer"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-endwise"
  merged = 0

# React and TypeScript Plugins
[[custom_plugins]]
  name = "mattn/emmet-vim"
  merged = 0
[[custom_plugins]]
  name = 'sheerun/vim-json'
  merged = 0
[[custom_plugins]]
  name = 'MaxMEllon/vim-jsx-pretty'
  merged = 0
[[custom_plugins]]
  name = 'peitalin/vim-jsx-typescript'
  merged = 0
[[custom_plugins]]
  name = 'HerringtonDarkholme/yats.vim'
  merged = 0
[[custom_plugins]]
  name = 'leafgarland/typescript-vim'
  merged = 0
[[custom_plugins]]
  name = 'styled-components/vim-styled-components'
  merged = 0
[[custom_plugins]]
  name = 'jparise/vim-graphql'
  merged = 0
[[custom_plugins]]
  name = 'prettier/vim-prettier'
  merged = 0
#disable for vim-jsx-improved
# [[custom_plugins]]
  # name = 'pangloss/vim-javascript'
  # merged = 0
[[custom_plugins]]
  name = 'chemzqm/vim-jsx-improve'
  merged = 0
[[custom_plugins]]
  name = 'mlaursen/vim-react-snippets'
  merged = 0

# Vue
# [[custom_plugins]]
  # name = 'leafOfTree/vim-vue-plugin'
  # merged = 0

# themes
[[custom_plugins]]
  name = 'rakr/vim-one'
  merged = 0
# [[custom_plugins]]
  # name = 'zeis/vim-kolor'
  # merged = 0
[[custom_plugins]]
  name = 'doums/darcula'
  merged = 0
[[custom_plugins]]
  name = 'glepnir/oceanic-material'
  merged = 0
# [[custom_plugins]]
  # name = 'srcery-colors/srcery-vim'
  # merged = 0
[[custom_plugins]]
  name = 'liuchengxu/space-vim-dark'
  merged = 0
[[custom_plugins]]
  name = 'liuchengxu/space-vim-theme'
  merged = 0
