#22=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    autocomplete_method = "coc"
    snippet_engine = "ultisnips"
    filemanager = "defx"
    lint_engine = "ale"
    colorscheme_bg = "dark"

    # colorscheme = "oceanic_material"
    # colorscheme = "gruvbox-material"
    # colorscheme = "molokai" # palenight, material, jellybeans, one, NeoSolarized, hybrid, SpaceVim, onedark, nord, molokai, srcery
    # colorscheme = "gruvbox8"
    colorscheme = "material"

    # enable_cursorcolumn = true
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # sidebar_width = 33
    # relativenumber=false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    # options for statusline
    # Set the statusline separators of statusline, default is "arrow"
    statusline_separator = "fire"
    # Set the statusline separators of inactive statusline
    statusline_inactive_separator = "bar"

    # Set SpaceVim buffer index type
    buffer_index_type = 0
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1

    # left sections of statusline
    # statusline_left_sections = [
       # 'winnr',
       # 'major mode',
       # 'filename',
       # 'fileformat',
       # 'minor mode lighters',
       # 'version control info',
       # 'search status'
    # ]

    # right sections of statusline
    statusline_right_sections = [
       'version control info',
       'cursorpos',
       'percentage',
       'input method',
       'date',	
       'time'
    ]

    # Display file type icon on the tabline, If you do not have nerd fonts
    enable_tabline_filetype_icon = true

    enable_statusline_mode = true

    # ignore node_modules when fuzzy finding
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"


# Languages and Utilities
[[layers]]
  name = "git"
# [[layers]]
  # name = "colorscheme"
[[layers]]
  name = 'edit'
  autosave_timeout = 300000
[[layers]]
  name = "debug"
  debugger_plugin = "vimspector"
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "nil"
  auto_completion_tab_key_behavior = "smart"
[[layers]]
  name = "tools" # calendar, goyo, limelight, vnoterainbow_parentheses, vimloo
[[layers]]
  name = "checkers"
[[layers]]
  name = "fzf"
[[layers]] # requires sudo apt install global
  name = "gtags"
  gtagslabel = "pygments" # or ctags
[[layers]]
  name = "lang#graphql"
[[layers]]
  name = "VersionControl"
[[layers]]
  name = "lang#ruby"
  enabled_linters = ['rubocop', 'rubylint']
[[layers]]
  name = "lang#kotlin"
[[layers]]
  name = "lang#html"
[[layers]]
 name = "lang#javascript" # npm install -g eslint, npm install -g js-beautify,  & touch ~/.eslintrc.json see docs
[[layers]]
  name = "lang#go"
[[layers]]
  name = "lang#rust"
[[layers]]
  name = "lsp"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "test"
[[layers]]
  name = "core#statusline"
[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

# Custom Plugins
[[custom_plugins]]
  name= "lambdalisue/glyph-palette.vim"
  merged = 0
[[custom_plugins]]
  name = "lilydjwg/colorizer"
  merged = 0

# React and TypeScript Plugins
[[custom_plugins]]
  name = 'sheerun/vim-polyglot'
  merged = 0
[[custom_plugins]]
  name = "mattn/emmet-vim"
  merged = 0
[[custom_plugins]]
  name = 'sheerun/vim-json'
  merged = 0
[[custom_plugins]]
  name = 'MaxMEllon/vim-jsx-pretty'
  merged = 0
[[custom_plugins]]
  name = 'HerringtonDarkholme/yats.vim'
  merged = 0
[[custom_plugins]]
  name = 'styled-components/vim-styled-components'
  merged = 0
[[custom_plugins]]
  name = 'jparise/vim-graphql'
  merged = 0
[[custom_plugins]]
  name = 'prettier/vim-prettier'
  merged = 0
[[custom_plugins]]
  name = 'chemzqm/vim-jsx-improve'
  merged = 0
[[custom_plugins]]
  name = 'mlaursen/vim-react-snippets'
  merged = 0

# Themes & Icons
[[custom_plugins]]
  name = 'glepnir/oceanic-material'
  merged = 0
[[custom_plugins]]
  name = 'sainnhe/gruvbox-material'
  merged = 0
[[custom_plugins]]
  name = 'lifepillar/vim-gruvbox8'
  merged = 0
[[custom_plugins]]
  name = "kaicataldo/material.vim"
  merged = 0

# ctags
# [[custom_plugins]]
  # name = 'github/copilot.vim'
  # merged = 0
[[custom_plugins]]
  name = 'tpope/rbenv-ctags'
  merged = 0
[[custom_plugins]]
  name = 'tpope/gem-ctags'
  merged = 0
[[custom_plugins]]
  name= "tpope/vim-bundler"
  merged = 0
[[custom_plugins]]
  name= "tpope/vim-rake"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-rails"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-haml"
  merged = 0
[[custom_plugins]]
  name = "slim-template/vim-slim"
  merged = 0
[[custom_plugins]]
  name = "sunaku/vim-ruby-minitest"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-endwise"
  merged = 0
