#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    autocomplete_method = "coc"
    snippet_engine = "ultisnips"
    filemanager = "defx"
    lint_engine = "ale"
    colorscheme_bg = "dark"

    # colorscheme = "oceanic_material"
    colorscheme = "gruvbox-material"
    # colorscheme = "everforest"

    # enable_cursorcolumn = true
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true

    # sidebar_width = 33
    # relativenumber=false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    # options for statusline
    # Set the statusline separators of statusline, default is "arrow"
    statusline_separator = "arrow"
    # Set the statusline separators of inactive statusline
    statusline_inactive_separator = "bar"

    # Set SpaceVim buffer index type
    buffer_index_type = 0
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1

    # left sections of statusline
    # statusline_left_sections = [
       # 'winnr',
       # 'major mode',
       # 'filename',
       # 'fileformat',
       # 'minor mode lighters',
       # 'version control info',
       # 'search status'
    # ]

    # right sections of statusline
    statusline_right_sections = [
       'version control info',
       'cursorpos',
       'percentage',
       'input method',
       'date',	
       'time'
    ]

    # Display file type icon on the tabline, If you do not have nerd fonts
    enable_tabline_filetype_icon = true

    enable_statusline_mode = true

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

# Languages and Utilities
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "nil"
  auto_completion_tab_key_behavior = "smart"
[[layers]]
  name = "checkers"
[[layers]]
  name = "lang#graphql"
[[layers]]
  name = "VersionControl"
[[layers]]
  name = "lang#ruby"
  enabled_linters = ['rubocop', 'rubylint']
[[layers]]
  name = "tmux"
[[layers]]
  name = "lang#kotlin"
[[layers]]
  name = "lang#html"
# [[layers]]
  # name = "lang#javascript"
  # enable_flow_syntax = true
# [[layers]]
  # name = "lang#typescript"
[[layers]]
  name = "lang#go"
[[layers]]
  name = "lsp"
[[layers]]
  name = "lang#markdown"
[[layers]]
  name = "test"
[[layers]]
  name = "core#statusline"
[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

# Custom Plugins
[[custom_plugins]]
  name= "lambdalisue/glyph-palette.vim"
  merged = 0
[[custom_plugins]]
  name = "slim-template/vim-slim"
  merged = 0
[[custom_plugins]]
  name = "sunaku/vim-ruby-minitest"
  merged = 0
[[custom_plugins]]
  name = "lilydjwg/colorizer"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-endwise"
  merged = 0

# React and TypeScript Plugins
[[custom_plugins]]
  name = "mattn/emmet-vim"
  merged = 0
[[custom_plugins]]
  name = 'sheerun/vim-json'
  merged = 0
[[custom_plugins]]
  name = 'MaxMEllon/vim-jsx-pretty'
  merged = 0
[[custom_plugins]]
  name = 'peitalin/vim-jsx-typescript'
  merged = 0
[[custom_plugins]]
  name = 'HerringtonDarkholme/yats.vim'
  merged = 0
[[custom_plugins]]
  name = 'leafgarland/typescript-vim'
  merged = 0
[[custom_plugins]]
  name = 'styled-components/vim-styled-components'
  merged = 0
[[custom_plugins]]
  name = 'jparise/vim-graphql'
  merged = 0
[[custom_plugins]]
  name = 'prettier/vim-prettier'
  merged = 0
[[custom_plugins]]
  name = 'chemzqm/vim-jsx-improve'
  merged = 0
[[custom_plugins]]
  name = 'mlaursen/vim-react-snippets'
  merged = 0

# Themes & Icons
[[custom_plugins]]
  name = 'glepnir/oceanic-material'
  merged = 0
[[custom_plugins]]
  name = 'sainnhe/gruvbox-material'
  merged = 0
[[custom_plugins]]
  name = 'sainnhe/everforest'
  merged = 0

# ctags
# [[custom_plugins]]
  # name = 'github/copilot.vim'
  # merged = 0
[[custom_plugins]]
  name = 'sheerun/vim-polyglot'
  merged = 0
[[custom_plugins]]
  name = 'tpope/rbenv-ctags'
  merged = 0
[[custom_plugins]]
  name = 'tpope/gem-ctags'
  merged = 0
[[custom_plugins]]
  name= "tpope/vim-fugitive"
  merged = 0
[[custom_plugins]]
  name= "tpope/vim-bundler"
  merged = 0
[[custom_plugins]]
  name= "tpope/vim-rake"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-rails"
  merged = 0
[[custom_plugins]]
  name = "tpope/vim-haml"
  merged = 0
[[custom_plugins]]
  name = "pocke/rbs.vim"
  merged = 0
