gui:
  showIcons: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  edit: 'lvim {{filename}}'
  editAtLine: 'lvim --line={{line}} {{filename}}'
  editAtLineAndWait: 'lvim --block --line={{line}} {{filename}}'
